import Header from "@/components/templates/layout/Header";
import "./globals.css";
import "./tailwind.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-custom-black text-custom-lightgray layout"}>
        <Header />

        <main className="mt-16">{children}</main>
      </body>
    </html>
  );
}
